version: "3.1"
services:
  master:
    image: agile-performance-jmeter-manager
    tty: true
    ports:
      - "60000"
    networks:
      - apj-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
          constraints: [node.role == manager]
  slave:
    image: agile-performance-jmeter-worker
    tty: true
    networks:
      - apj-network
    ports:
      - "50000"
      - "1099"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]
networks:
  apj-network:
